### PR TITLE
Updated travis to use docker CouchDB

### PR DESCRIPTION
**Pull request by ricellis**
Thanks for your hard work, please ensure all items are complete before opening.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://github.com/cloudant-labs/kafka-connect-cloudant/blob/master/DCO1.1.txt)
- [x] You have added tests for any code changes - **test only changes**
- [x] You have updated the [CHANGES.md](https://github.com/cloudant-labs/kafka-connect-cloudant/blob/master/CHANGES.md) - **N/A test only changes**
- [x] You have completed the PR template below:

## What

Changed `.travis.yml` to use local docker `apache/couchdb`

## Testing

CI passing.

## Issues

N/A

### CODE REVIEW

**Comment by ricellis** [comment]
I could update it to `couchdb:2` which I think gets the latest `2.x`. I didn't see an equivalent tag documented for `apache/couchdb`.
I'm not sure on the status between `couchdb` (apparently official) and `apache/couchdb` (apparently unofficial). I thought all the Apache projects were putting official images in `apache/` now.

**Comment by emlaver** [comment]
@ricellis Maybe it's better to use `library/couchdb` which I believe is official.

**Comment by ricellis** [comment]
The [CouchDB docs say use `apache/couchdb`](http://docs.couchdb.org/en/latest/install/docker.html#installation-via-docker) though. I've asked for clarification from the community.

**Comment by ricellis** [comment]
Merging for now, we can update the docker image to `couchdb:2` later if I get any clarification on it.

**Pull request merged**
