### PR TITLE
Add release script

### PR DESCRIPTION
**Pull request by asarantes**
Add support to run maven release prepare and publish
as well as the ability to publish snapshots

### CODE REVIEW

**Comment by HolgerKache** [comment]
@asarantes The maven build works fine. What I could not complete is the test for the release script. Here is what I run: 

````
./release.sh --release-prepare --releaseVersion="1.0.0" --developmentVersion="1.1.0-SNAPSHOT" --dryRun
The environment variable GPG_PASSPHRASE is not set. Enter the passphrase to
unlock the GPG signing key that will be used to sign the release!

GPG passphrase:
````

How do I get that GPG passphrase from http://www.sonatype.org/nexus/ ? Do we have to sign up individually or do we supply a shared set of credentials we can use?

One more request: can you please modify the README with instructions on

**Comment by asarantes** [comment]
You need to install GPG tools on your machine. Here are some steps to do it. Hopefully it is complete.

2. Install gpg tools mac

Look for gpg tools mac installation for example. Download the installer.

2.1 Follow steps during installation to generate key. Create a passphrase.
2.2 Make sure the server is an acceptable one (otherwise you will get error when
uploading the jar to the maven repo)
  a) Go to Preferences/Key Server. The following is acceptable.
  hkp://pgp.mit.edu
  b) Right click on key then choose Send public key to key server
2.3 Export GPG_PASSPHRASE env variable with your passphrase you used to create the key
Ex:
export GPG_PASSPHRASE=<your passphrase>

It's better you put this export on your bashrc or bash_profile.

Do you have an account on Sonatype maven repo? Otherwise you will need to create it and request access to our repository so you can see what I showed in our demo.

Maven Repo Process
=========================================================
1. Follow steps 1 and 2 to create a ticket with Sonatype from this link (Initial setup)
http://central.sonatype.org/pages/ossrh-guide.html
a. Create a JIRA account
b. Create an issue

Your issue should request access to our repository which is already created instead of creating a new one.

Yes I can. Let me know how detailed you want that to be.

**Comment by asarantes** [comment]
Added a Release Notes section in the readme file.

**Comment by HolgerKache** [comment]
+1

@asarantes thanks for the detailed instructions now in the README. I know you tested this so the PR is good. I will merge this as you still don't have your permissions.

**Pull request merged**
