### PR TITLE
Add build support via Travis CI

### PR DESCRIPTION
**Pull request by asarantes**
Please merge this after #11

### CODE REVIEW

**Comment by HolgerKache** [comment]
The .travis.yml looks good according to `travis lint .travis.yml`.

In addition to the build with ` -Dmaven.test.skip=true` I would actually like to run the tests with every build.

Can we introduce the `after_deploy` phase where we run `mvn test`? The phase will have to do some string substitution in the `src/test/resources/test.properties` file first. Expected values for Cloudant account/user/password should come from variables we specify in Travis (e.g. CLOUDANT_ACCOUNT) and reference in the .travis.yml with ${CLOUDANT_ACCOUNT}. Note that variables can have _secret_ values.

**Comment by HolgerKache** [comment]
@asarantes Have a look at https://travis.ibm.com/dap/streams-services/settings in combination with https://github.ibm.com/dap/streams-services/blob/master/.travis.yml if you need a reference on how to do the test execution.

**Comment by asarantes** [comment]
String substitution would be fine and I think we could run a test after a successful build or even together just not skipping tests. Please, correct me if I'm wrong but I think connectors need a local Kafka cluster which means we would need to install a Kafka Cluster in Travis, correct? I assume it is possible to do this in Travis and we would have enough power to start up the cluster and run our tests. 

I can't see the settings in here https://travis.ibm.com/dap/streams-services/settings probably because of permission issues but I think I know what you mean.

**Comment by asarantes** [comment]
Support for tests to be executed in every build has been added in the .travis.yml file.
The following env variables needs to be set in Travis: CLOUDANT_ACCOUNT, CLOUDANT_USERNAME, CLOUDANT_DB, CLOUDANT_PASSWORD

**Comment by HolgerKache** [comment]
Travis build and tests work well now. One small problem to address. The test runs with a INFO log output and exposes the test account credentials in the logs.

The log contains this INFO level output like 

```
Running com.ibm.cloudant.kafka.connect.CloudantSourceConnectorTest

2017-02-06 11:09:14 INFO  CloudantSourceConnectorConfig - CloudantSourceConnectorConfig values: 

	cloudant.db.password = (clear text pwd)

	cloudant.db.since = 0

	cloudant.db.url = https://kache.cloudant.com/travis-test

	cloudant.db.username = kache

	topics = [test-topic]
```

+1 after that fix.

**Comment by asarantes** [comment]
Fixed by changing log level.

**Pull request closed without merging**
